services:
  - type: web
    name: portfolio-dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python Dashboard_panel/dashboard_cardinality.py
    healthCheckPath: /health
    autoDeploy: true
